project_name: example-go-slsa-provenance
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/example-go-slsa-provenance
    binary: example-go-slsa-provenance
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
release:
  draft: true # we update release note manually before releasing
