name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write # required to create a release
  id-token: write # required for cosign
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.3"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # tag=v3.2.0
        with:
          version: latest
          args: release --rm-dist --skip-publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/*.tar.gz
            dist/*.sig
            dist/*.pem
            dist/*_checksums.txt
      - name: Generate hashes
        id: hash
        run: |
          # sha256sum generates sha256 hash for all artifacts.
          # base64 -w0 encodes to base64 and outputs on a single line.
          # sha256sum artifact1 artifact2 ... | base64 -w0
          echo "hashes=$(find dist -name "*.tar.gz" -print0 | xargs -0 sha256sum | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [build]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      # Upload provenance to a new release
      upload-assets: false

  release:
    needs: [provenance]
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p dist/artifacts dist/provenance
      - name: Download the provenance
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.provenance.outputs.provenance-name }}
          path: dist/provenance/${{ needs.provenance.outputs.provenance-name }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: dist/artifacts

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          prerelease: true
          files: |
            dist/**/*
